default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # match(type: "appstore") # Get certificates
    # build_app(workspace: "ios/SwagLabsMobileApp.xcworkspace", scheme: "SwagLabsMobileApp")
    # upload_to_testflight
  end

  desc "Push a new build to Firebase App Distribution for internal testing"
  lane :internal do
    # match(type: "development")
    # build_app(workspace: "ios/SwagLabsMobileApp.xcworkspace", scheme: "SwagLabsMobileApp")
    # firebase_app_distribution(
    #   app: ENV["FIREBASE_APP_ID_IOS"],
    #   groups: "qa-team"
    # )
  end
end

platform :android do
  desc "Push a new beta build to Firebase App Distribution"
  lane :internal do
    # gradle(task: "clean assembleDebug", project_dir: "android/")
    # firebase_app_distribution(
    #   app: ENV["FIREBASE_APP_ID_ANDROID"],
    #   groups: "qa-team"
    # )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    # gradle(task: "clean bundleRelease", project_dir: "android/")
    # upload_to_play_store
  end
end
